name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: booking
          MYSQL_USER: booking_user
          MYSQL_PASSWORD: booking_pass
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: |
          dotnet restore ./booking-system/booking-system.csproj
          dotnet restore ./booking-system.Tests/booking-system.Tests.csproj

      - name: Run tests
        env:
          ConnectionStrings__DefaultConnection: "server=127.0.0.1;port=3306;database=booking;user=booking_user;password=booking_pass"
        run: dotnet test ./booking-system.Tests/booking-system.Tests.csproj --no-restore

