name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Clean NuGet cache
        run: dotnet nuget locals all --clear

      - name: Restore dependencies
        run: dotnet restore

      - name: Run tests
        run: dotnet test ./booking-system.Tests/booking-system.Tests.csproj --no-restore --verbosity normal

      - name: Build Docker image
        run: docker build -t booking-system ./booking-system
